# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgcompare < Formula
  desc "PostgreSQL query performance comparison tool for students"
  homepage "https://github.com/pg-tools/pgcompare"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pg-tools/pgcompare/releases/download/v1.1.0/pgcompare_darwin_amd64.tar.gz"
      sha256 "2666f8bef834a47725944511fd939a42a33759347a9438d93cc19d80fedbbc6a"

      define_method(:install) do
        bin.install "pgcompare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pg-tools/pgcompare/releases/download/v1.1.0/pgcompare_darwin_arm64.tar.gz"
      sha256 "3aea0605e0a6f3c73b44f8bfc82ba216109eeddbd52a003d244d7d69d0bf3288"

      define_method(:install) do
        bin.install "pgcompare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pg-tools/pgcompare/releases/download/v1.1.0/pgcompare_linux_amd64.tar.gz"
      sha256 "f4905fe50f2122d4125175c6e3236df4de1c341fdc6ba38da199dbee6268deef"
      define_method(:install) do
        bin.install "pgcompare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pg-tools/pgcompare/releases/download/v1.1.0/pgcompare_linux_arm64.tar.gz"
      sha256 "e7bd006ffe8789c6c6c0d7d46987375f29399b60856732d599727ad80d41dda6"
      define_method(:install) do
        bin.install "pgcompare"
      end
    end
  end
end
