# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgcompare < Formula
  desc "PostgreSQL query performance comparison tool for students"
  homepage "https://github.com/pg-tools/pgcompare"
  version "1.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pg-tools/pgcompare/releases/download/v1.2.3/pgcompare_darwin_amd64.tar.gz"
      sha256 "ec261c29fd4b28fa36576d921559ea7b0e34559b83aa4d82bd5b24fe46a25278"

      define_method(:install) do
        bin.install "pgcompare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pg-tools/pgcompare/releases/download/v1.2.3/pgcompare_darwin_arm64.tar.gz"
      sha256 "8f21e07b687ec5d9af3385d6a5a38b7b3206722e09e70c1f832d17564883ac71"

      define_method(:install) do
        bin.install "pgcompare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pg-tools/pgcompare/releases/download/v1.2.3/pgcompare_linux_amd64.tar.gz"
      sha256 "7366f2e7d102cd047ed92d7dd93ebb443055349d1b215da2fab8ff64136139d0"
      define_method(:install) do
        bin.install "pgcompare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pg-tools/pgcompare/releases/download/v1.2.3/pgcompare_linux_arm64.tar.gz"
      sha256 "07c34f472b91ccaeb5a149e9bdfe8b04635a96513228f907d59ae72fb0e802eb"
      define_method(:install) do
        bin.install "pgcompare"
      end
    end
  end
end
